Feature/microsites managment
luisJaimeB/placetogrowms pull request #5
Opened 2024-07-01 04:09 UTC by luisJaimeB

2024-07-05 15:41 UTC, parrotsoft requested changes

2024-07-05 15:41 UTC, parrotsoft commented on app/Actions/CreateMicrositeAction.php
> +use Illuminate\Support\Facades\Storage;
Las clases que no se utilizan deben ser removidas del codigo, es mala practica dejarlas.

2024-07-05 15:41 UTC, parrotsoft commented on app/Actions/CreateMicrositeAction.php
> +        $microsite->save();
Esta funcion retorna un bool que podrias utilizar para validar el guardado correcto del logo.

2024-07-05 15:41 UTC, parrotsoft commented on app/Actions/CreateMicrositeAction.php
> +    public function __construct(private array $data)
El constructor tiene sentido para respetar algunos principios de POO, pero me podría mejorar esta clase manejando una solo función Execute estática que reciba como argumento el array de los datos.

2024-07-05 15:41 UTC, parrotsoft commented on app/Actions/UpdateMicrositeAction.php
> +        } else {
Esto que es ? un else sin cuerpo ? validar esto.

2024-07-05 15:41 UTC, parrotsoft commented on app/Actions/UpdateMicrositeAction.php
> +            $disk = "public_upload";
Recomendación, este tipo de datos normalmente se asignan a un constante en la parte superior de la clase.

2024-07-05 15:41 UTC, parrotsoft commented on app/Actions/UpdateMicrositeAction.php
> +        $this->microsite->save();
Lo mismo que la accion anterior, esto retorna un bool que puedes utilizar para validar el guardado correcto del archivo.

2024-07-05 15:41 UTC, parrotsoft commented on app/Http/Controllers/MicrositeController.php
> +use App\Constants\TypesSites;
Remover clases que no se utilizan en este controlador.

2024-07-05 15:41 UTC, parrotsoft commented on app/Http/Controllers/MicrositeController.php
> +    public function index()
El tipado de retorno para este metodo ?

2024-07-05 15:41 UTC, parrotsoft commented on app/Http/Controllers/MicrositeController.php
Validar el tipado de retorno para todos los metodos de esta clase.

2024-07-05 15:41 UTC, parrotsoft commented on app/Http/Middleware/HandleInertiaRequests.php
> +    private function getTranslations()
El tipado de esta funcion ?

2024-07-05 15:41 UTC, parrotsoft commented on database/factories/MicrositeFactory.php
Para la generación de los datos dependientes (otras tablas) lo mejor es utilizar las factorías de cada Modelo. 
Algo asi:
'type_site_id' => TypeSite::factory()->create(),

2024-07-05 15:41 UTC, parrotsoft commented on database/migrations/2024_06_29_154201_create_type_sites_table.php
> +            $table->string('name');
el nombre del type_sites tendria mas control si es unico.

2024-07-05 15:41 UTC, parrotsoft commented on database/migrations/2024_06_29_221625_create_categories_table.php
> +            $table->string('name');
El nombre debe ser unico.

2024-07-05 15:41 UTC, parrotsoft commented on database/migrations/2024_06_29_221642_create_microsites_table.php
> +            $table->string('name');
El nombre debe ser unico

2024-07-05 15:41 UTC, parrotsoft commented on database/migrations/2024_06_29_221743_create_currencies_table.php
> +            $table->string('code');
el code deben ser unicos y name, puedes armar una llave entre los dos campos.

2024-07-05 15:41 UTC, parrotsoft commented on database/seeders/CategorySeeder.php
> +    {
es mas elegante esto:
```php
$categories = [
	'education',
	'marketer',
	'services',
];

foreace($categories as $categorie) {
	Category::create([
            'name' => $categorie,
        ]);
}
```

2024-07-05 15:41 UTC, parrotsoft commented on database/seeders/RoleAndPermissionSeeder.php
Validar clases que no se utilizan

2024-07-05 15:41 UTC, parrotsoft commented on database/seeders/TypeSiteSeeder.php
Pueder mejorar este codigo con una forma mas elegante.

2024-07-05 15:41 UTC, parrotsoft commented on resources/js/Components/microsites/Form.vue
Las traducciones de los label?

2024-07-05 15:41 UTC, parrotsoft commented on resources/js/Components/microsites/FormEdit.vue
Traducciones ?

2024-07-05 15:41 UTC, parrotsoft commented on resources/js/Layouts/AuthenticatedLayout.vue
Traducciones?

2024-07-05 15:41 UTC, parrotsoft commented on routes/web.php
> +    Route::get('/microsites', [MicrositeController::class, 'index'])->middleware('can:microsites.index')->name('microsites.index');
Indagar sobre como en laravel se pueden agrupar los recursos (rutas)

2024-07-05 15:41 UTC, parrotsoft commented on tests/Feature/Microsites/MicrositeCreateTest.php
> +    private const RESOURCE_NAME = 'microsites.create';
el tipado de la constante ?

2024-07-05 15:41 UTC, parrotsoft commented on tests/Feature/Microsites/MicrositeCreateTest.php
Remover clases que no utilizas

2024-07-05 15:41 UTC, parrotsoft commented on tests/Feature/Microsites/MicrositeCreateTest.php
> +        $adminRole = Role::create(['name' => 'Admin']);
Para esto debes utilizar las factory de ese modelo, no es bueno trabajar directamente con el modelo.

2024-07-05 15:41 UTC, parrotsoft commented on tests/Feature/Microsites/MicrositeDestroyTest.php
> +    private const RESOURCE_NAME = 'microsites.destroy';
el tipado de la constante ?

2024-07-05 15:41 UTC, parrotsoft commented on tests/Feature/Microsites/MicrositeDestroyTest.php
Remover clases que no utilizas

2024-07-05 15:41 UTC, parrotsoft commented on tests/Feature/Microsites/MicrositeEditTest.php
Igual que los demas test.

2024-08-01 20:16 UTC, parrotsoft approved these changes
Mucho mejor, detalles de forma pero nada del otro mundo, por favor validar este error al instalar tu proyecto en local desde 0. 
![Screenshot 2024-08-01 at 3 12 28 PM](https://github.com/user-attachments/assets/8dee28fb-fcad-49b1-af70-e3b22f15f5c5)

2024-08-05 00:37 UTC, luisJaimeB commented
Functionality to create, edit, view, list and general administration of the microsites section, where it is intended to add the payment button to carry out the connection with payment gateway.

2024-08-05 00:38 UTC, merged